// @generated by protoc-gen-es v1.3.1
// @generated from file common/common.proto (package cafelogos.common, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message cafelogos.common.Empty
 */
export const Empty = proto3.makeMessageType(
  "cafelogos.common.Empty",
  [],
);

