// Code generated by protoc-gen-connect-swift. DO NOT EDIT.
//
// Source: orderlink/orderlink_service.proto
//

import Connect
import Foundation
import SwiftProtobuf

public protocol Cafelogos_Orderlink_OrderLinkServiceClientInterface: Sendable {

    @discardableResult
    func `postOrder`(request: Cafelogos_Orderlink_PostOrderInput, headers: Connect.Headers, completion: @escaping @Sendable (ResponseMessage<Cafelogos_Common_Empty>) -> Void) -> Connect.Cancelable

    @available(iOS 13, *)
    func `postOrder`(request: Cafelogos_Orderlink_PostOrderInput, headers: Connect.Headers) async -> ResponseMessage<Cafelogos_Common_Empty>
}

/// Concrete implementation of `Cafelogos_Orderlink_OrderLinkServiceClientInterface`.
public final class Cafelogos_Orderlink_OrderLinkServiceClient: Cafelogos_Orderlink_OrderLinkServiceClientInterface, Sendable {
    private let client: Connect.ProtocolClientInterface

    public init(client: Connect.ProtocolClientInterface) {
        self.client = client
    }

    @discardableResult
    public func `postOrder`(request: Cafelogos_Orderlink_PostOrderInput, headers: Connect.Headers = [:], completion: @escaping @Sendable (ResponseMessage<Cafelogos_Common_Empty>) -> Void) -> Connect.Cancelable {
        return self.client.unary(path: "/cafelogos.orderlink.OrderLinkService/PostOrder", idempotencyLevel: .unknown, request: request, headers: headers, completion: completion)
    }

    @available(iOS 13, *)
    public func `postOrder`(request: Cafelogos_Orderlink_PostOrderInput, headers: Connect.Headers = [:]) async -> ResponseMessage<Cafelogos_Common_Empty> {
        return await self.client.unary(path: "/cafelogos.orderlink.OrderLinkService/PostOrder", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    public enum Metadata {
        public enum Methods {
            public static let postOrder = Connect.MethodSpec(name: "PostOrder", service: "cafelogos.orderlink.OrderLinkService", type: .unary)
        }
    }
}
