// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: ticket/ticket_service.proto

package ticket

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestIssueTicket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prefix string `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
}

func (x *RequestIssueTicket) Reset() {
	*x = RequestIssueTicket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ticket_ticket_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestIssueTicket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestIssueTicket) ProtoMessage() {}

func (x *RequestIssueTicket) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_ticket_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestIssueTicket.ProtoReflect.Descriptor instead.
func (*RequestIssueTicket) Descriptor() ([]byte, []int) {
	return file_ticket_ticket_service_proto_rawDescGZIP(), []int{0}
}

func (x *RequestIssueTicket) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type ResponseIssueTicket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ticket *Ticket `protobuf:"bytes,1,opt,name=ticket,proto3" json:"ticket,omitempty"`
}

func (x *ResponseIssueTicket) Reset() {
	*x = ResponseIssueTicket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ticket_ticket_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseIssueTicket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseIssueTicket) ProtoMessage() {}

func (x *ResponseIssueTicket) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_ticket_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseIssueTicket.ProtoReflect.Descriptor instead.
func (*ResponseIssueTicket) Descriptor() ([]byte, []int) {
	return file_ticket_ticket_service_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseIssueTicket) GetTicket() *Ticket {
	if x != nil {
		return x.Ticket
	}
	return nil
}

type RequestRevokeTicket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RequestRevokeTicket) Reset() {
	*x = RequestRevokeTicket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ticket_ticket_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestRevokeTicket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestRevokeTicket) ProtoMessage() {}

func (x *RequestRevokeTicket) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_ticket_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestRevokeTicket.ProtoReflect.Descriptor instead.
func (*RequestRevokeTicket) Descriptor() ([]byte, []int) {
	return file_ticket_ticket_service_proto_rawDescGZIP(), []int{2}
}

func (x *RequestRevokeTicket) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ResponseRevokeTicket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ResponseRevokeTicket) Reset() {
	*x = ResponseRevokeTicket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ticket_ticket_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseRevokeTicket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseRevokeTicket) ProtoMessage() {}

func (x *ResponseRevokeTicket) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_ticket_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseRevokeTicket.ProtoReflect.Descriptor instead.
func (*ResponseRevokeTicket) Descriptor() ([]byte, []int) {
	return file_ticket_ticket_service_proto_rawDescGZIP(), []int{3}
}

type Ticket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// PrefixとNumberを結合したもの
	TicketAddr string `protobuf:"bytes,2,opt,name=ticket_addr,json=ticketAddr,proto3" json:"ticket_addr,omitempty"`
	CreatedAt  string `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *Ticket) Reset() {
	*x = Ticket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ticket_ticket_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ticket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ticket) ProtoMessage() {}

func (x *Ticket) ProtoReflect() protoreflect.Message {
	mi := &file_ticket_ticket_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ticket.ProtoReflect.Descriptor instead.
func (*Ticket) Descriptor() ([]byte, []int) {
	return file_ticket_ticket_service_proto_rawDescGZIP(), []int{4}
}

func (x *Ticket) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Ticket) GetTicketAddr() string {
	if x != nil {
		return x.TicketAddr
	}
	return ""
}

func (x *Ticket) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_ticket_ticket_service_proto protoreflect.FileDescriptor

var file_ticket_ticket_service_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x2f, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x63,
	0x61, 0x66, 0x65, 0x6c, 0x6f, 0x67, 0x6f, 0x73, 0x2e, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x22,
	0x2c, 0x0a, 0x12, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x73, 0x73, 0x75, 0x65, 0x54,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x22, 0x47, 0x0a,
	0x13, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x49, 0x73, 0x73, 0x75, 0x65, 0x54, 0x69,
	0x63, 0x6b, 0x65, 0x74, 0x12, 0x30, 0x0a, 0x06, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63, 0x61, 0x66, 0x65, 0x6c, 0x6f, 0x67, 0x6f, 0x73,
	0x2e, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x06,
	0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x22, 0x25, 0x0a, 0x13, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x52, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x16, 0x0a,
	0x14, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x54,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x22, 0x58, 0x0a, 0x06, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x1f, 0x0a, 0x0b, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72,
	0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x32,
	0xce, 0x01, 0x0a, 0x0d, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x5c, 0x0a, 0x0b, 0x49, 0x73, 0x73, 0x75, 0x65, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74,
	0x12, 0x24, 0x2e, 0x63, 0x61, 0x66, 0x65, 0x6c, 0x6f, 0x67, 0x6f, 0x73, 0x2e, 0x74, 0x69, 0x63,
	0x6b, 0x65, 0x74, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x73, 0x73, 0x75, 0x65,
	0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x1a, 0x25, 0x2e, 0x63, 0x61, 0x66, 0x65, 0x6c, 0x6f, 0x67,
	0x6f, 0x73, 0x2e, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x49, 0x73, 0x73, 0x75, 0x65, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x22, 0x00, 0x12,
	0x5f, 0x0a, 0x0c, 0x52, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x12,
	0x25, 0x2e, 0x63, 0x61, 0x66, 0x65, 0x6c, 0x6f, 0x67, 0x6f, 0x73, 0x2e, 0x74, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x76, 0x6f, 0x6b, 0x65,
	0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x1a, 0x26, 0x2e, 0x63, 0x61, 0x66, 0x65, 0x6c, 0x6f, 0x67,
	0x6f, 0x73, 0x2e, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x52, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x22, 0x00,
	0x42, 0x3b, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4b,
	0x61, 0x67, 0x75, 0x72, 0x61, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x63, 0x61, 0x66,
	0x65, 0x6c, 0x6f, 0x67, 0x6f, 0x73, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x3b, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ticket_ticket_service_proto_rawDescOnce sync.Once
	file_ticket_ticket_service_proto_rawDescData = file_ticket_ticket_service_proto_rawDesc
)

func file_ticket_ticket_service_proto_rawDescGZIP() []byte {
	file_ticket_ticket_service_proto_rawDescOnce.Do(func() {
		file_ticket_ticket_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_ticket_ticket_service_proto_rawDescData)
	})
	return file_ticket_ticket_service_proto_rawDescData
}

var file_ticket_ticket_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_ticket_ticket_service_proto_goTypes = []interface{}{
	(*RequestIssueTicket)(nil),   // 0: cafelogos.ticket.RequestIssueTicket
	(*ResponseIssueTicket)(nil),  // 1: cafelogos.ticket.ResponseIssueTicket
	(*RequestRevokeTicket)(nil),  // 2: cafelogos.ticket.RequestRevokeTicket
	(*ResponseRevokeTicket)(nil), // 3: cafelogos.ticket.ResponseRevokeTicket
	(*Ticket)(nil),               // 4: cafelogos.ticket.Ticket
}
var file_ticket_ticket_service_proto_depIdxs = []int32{
	4, // 0: cafelogos.ticket.ResponseIssueTicket.ticket:type_name -> cafelogos.ticket.Ticket
	0, // 1: cafelogos.ticket.TicketService.IssueTicket:input_type -> cafelogos.ticket.RequestIssueTicket
	2, // 2: cafelogos.ticket.TicketService.RevokeTicket:input_type -> cafelogos.ticket.RequestRevokeTicket
	1, // 3: cafelogos.ticket.TicketService.IssueTicket:output_type -> cafelogos.ticket.ResponseIssueTicket
	3, // 4: cafelogos.ticket.TicketService.RevokeTicket:output_type -> cafelogos.ticket.ResponseRevokeTicket
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ticket_ticket_service_proto_init() }
func file_ticket_ticket_service_proto_init() {
	if File_ticket_ticket_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ticket_ticket_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestIssueTicket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ticket_ticket_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseIssueTicket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ticket_ticket_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestRevokeTicket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ticket_ticket_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseRevokeTicket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ticket_ticket_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ticket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ticket_ticket_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ticket_ticket_service_proto_goTypes,
		DependencyIndexes: file_ticket_ticket_service_proto_depIdxs,
		MessageInfos:      file_ticket_ticket_service_proto_msgTypes,
	}.Build()
	File_ticket_ticket_service_proto = out.File
	file_ticket_ticket_service_proto_rawDesc = nil
	file_ticket_ticket_service_proto_goTypes = nil
	file_ticket_ticket_service_proto_depIdxs = nil
}
