// @generated by protoc-gen-connect-query v2.0.1 with parameter "target=ts+js+dts"
// @generated from file pos/pos_service.proto (package cafelogos.pos, syntax proto3)
/* eslint-disable */

import { PosService } from "./pos_service_pb";

/**
 * @generated from rpc cafelogos.pos.PosService.GetOrders
 */
export const getOrders: typeof PosService["method"]["getOrders"];
/**
 * @generated from rpc cafelogos.pos.PosService.GetUnpaidOrdersBySeatId
 */
export const getUnpaidOrdersBySeatId: typeof PosService["method"]["getUnpaidOrdersBySeatId"];
/**
 * @generated from rpc cafelogos.pos.PosService.PostOrder
 */
export const postOrder: typeof PosService["method"]["postOrder"];
/**
 * @generated from rpc cafelogos.pos.PosService.DeleteOrder
 */
export const deleteOrder: typeof PosService["method"]["deleteOrder"];
/**
 * @generated from rpc cafelogos.pos.PosService.PostPayment
 */
export const postPayment: typeof PosService["method"]["postPayment"];
/**
 * @generated from rpc cafelogos.pos.PosService.UpdatePayment
 */
export const updatePayment: typeof PosService["method"]["updatePayment"];
/**
 * @generated from rpc cafelogos.pos.PosService.GetExternalPayment
 */
export const getExternalPayment: typeof PosService["method"]["getExternalPayment"];
/**
 * @generated from rpc cafelogos.pos.PosService.GetProducts
 */
export const getProducts: typeof PosService["method"]["getProducts"];
/**
 * @generated from rpc cafelogos.pos.PosService.PostNewClient
 */
export const postNewClient: typeof PosService["method"]["postNewClient"];
/**
 * @generated from rpc cafelogos.pos.PosService.UpdateClient
 */
export const updateClient: typeof PosService["method"]["updateClient"];
/**
 * Only Admin
 *
 * @generated from rpc cafelogos.pos.PosService.GetProductCategories
 */
export const getProductCategories: typeof PosService["method"]["getProductCategories"];
/**
 * @generated from rpc cafelogos.pos.PosService.PostProductCategory
 */
export const postProductCategory: typeof PosService["method"]["postProductCategory"];
/**
 * @generated from rpc cafelogos.pos.PosService.PostProduct
 */
export const postProduct: typeof PosService["method"]["postProduct"];
/**
 * @generated from rpc cafelogos.pos.PosService.UpdateProduct
 */
export const updateProduct: typeof PosService["method"]["updateProduct"];
/**
 * @generated from rpc cafelogos.pos.PosService.DeleteProduct
 */
export const deleteProduct: typeof PosService["method"]["deleteProduct"];
/**
 * @generated from rpc cafelogos.pos.PosService.PostStock
 */
export const postStock: typeof PosService["method"]["postStock"];
/**
 * @generated from rpc cafelogos.pos.PosService.GetStocks
 */
export const getStocks: typeof PosService["method"]["getStocks"];
/**
 * @generated from rpc cafelogos.pos.PosService.UpdateStock
 */
export const updateStock: typeof PosService["method"]["updateStock"];
/**
 * @generated from rpc cafelogos.pos.PosService.PostCoffeeBean
 */
export const postCoffeeBean: typeof PosService["method"]["postCoffeeBean"];
/**
 * @generated from rpc cafelogos.pos.PosService.GetCoffeeBeans
 */
export const getCoffeeBeans: typeof PosService["method"]["getCoffeeBeans"];
/**
 * @generated from rpc cafelogos.pos.PosService.DeleteAllOrders
 */
export const deleteAllOrders: typeof PosService["method"]["deleteAllOrders"];
/**
 * @generated from rpc cafelogos.pos.PosService.PostSeat
 */
export const postSeat: typeof PosService["method"]["postSeat"];
/**
 * @generated from rpc cafelogos.pos.PosService.UpdateSeat
 */
export const updateSeat: typeof PosService["method"]["updateSeat"];
/**
 * @generated from rpc cafelogos.pos.PosService.DeleteSeat
 */
export const deleteSeat: typeof PosService["method"]["deleteSeat"];
/**
 * @generated from rpc cafelogos.pos.PosService.GetSeats
 */
export const getSeats: typeof PosService["method"]["getSeats"];
/**
 * @generated from rpc cafelogos.pos.PosService.GetDiscounts
 */
export const getDiscounts: typeof PosService["method"]["getDiscounts"];
/**
 * @generated from rpc cafelogos.pos.PosService.PostDiscount
 */
export const postDiscount: typeof PosService["method"]["postDiscount"];
/**
 * @generated from rpc cafelogos.pos.PosService.GetDailySales
 */
export const getDailySales: typeof PosService["method"]["getDailySales"];
/**
 * @generated from rpc cafelogos.pos.PosService.GetProductSales
 */
export const getProductSales: typeof PosService["method"]["getProductSales"];
/**
 * 売上分析用のメソッド
 *
 * @generated from rpc cafelogos.pos.PosService.GetSalesByTimeSlot
 */
export const getSalesByTimeSlot: typeof PosService["method"]["getSalesByTimeSlot"];
/**
 * @generated from rpc cafelogos.pos.PosService.GetSalesByPaymentType
 */
export const getSalesByPaymentType: typeof PosService["method"]["getSalesByPaymentType"];
