// @generated by protoc-gen-connect-query v2.0.1 with parameter "target=ts+js+dts"
// @generated from file pos/pos_service.proto (package cafelogos.pos, syntax proto3)
/* eslint-disable */

import { PosService } from "./pos_service_pb";

/**
 * @generated from rpc cafelogos.pos.PosService.GetOrders
 */
export const getOrders = PosService.method.getOrders;

/**
 * @generated from rpc cafelogos.pos.PosService.GetUnpaidOrdersBySeatId
 */
export const getUnpaidOrdersBySeatId = PosService.method.getUnpaidOrdersBySeatId;

/**
 * @generated from rpc cafelogos.pos.PosService.PostOrder
 */
export const postOrder = PosService.method.postOrder;

/**
 * @generated from rpc cafelogos.pos.PosService.DeleteOrder
 */
export const deleteOrder = PosService.method.deleteOrder;

/**
 * @generated from rpc cafelogos.pos.PosService.PostPayment
 */
export const postPayment = PosService.method.postPayment;

/**
 * @generated from rpc cafelogos.pos.PosService.UpdatePayment
 */
export const updatePayment = PosService.method.updatePayment;

/**
 * @generated from rpc cafelogos.pos.PosService.GetExternalPayment
 */
export const getExternalPayment = PosService.method.getExternalPayment;

/**
 * @generated from rpc cafelogos.pos.PosService.RefundPayment
 */
export const refundPayment = PosService.method.refundPayment;

/**
 * @generated from rpc cafelogos.pos.PosService.GetProducts
 */
export const getProducts = PosService.method.getProducts;

/**
 * @generated from rpc cafelogos.pos.PosService.PostNewClient
 */
export const postNewClient = PosService.method.postNewClient;

/**
 * @generated from rpc cafelogos.pos.PosService.UpdateClient
 */
export const updateClient = PosService.method.updateClient;

/**
 * Only Admin
 *
 * @generated from rpc cafelogos.pos.PosService.GetProductCategories
 */
export const getProductCategories = PosService.method.getProductCategories;

/**
 * @generated from rpc cafelogos.pos.PosService.PostProductCategory
 */
export const postProductCategory = PosService.method.postProductCategory;

/**
 * @generated from rpc cafelogos.pos.PosService.PostProduct
 */
export const postProduct = PosService.method.postProduct;

/**
 * @generated from rpc cafelogos.pos.PosService.UpdateProduct
 */
export const updateProduct = PosService.method.updateProduct;

/**
 * @generated from rpc cafelogos.pos.PosService.DeleteProduct
 */
export const deleteProduct = PosService.method.deleteProduct;

/**
 * @generated from rpc cafelogos.pos.PosService.PostStock
 */
export const postStock = PosService.method.postStock;

/**
 * @generated from rpc cafelogos.pos.PosService.GetStocks
 */
export const getStocks = PosService.method.getStocks;

/**
 * @generated from rpc cafelogos.pos.PosService.UpdateStock
 */
export const updateStock = PosService.method.updateStock;

/**
 * @generated from rpc cafelogos.pos.PosService.PostCoffeeBean
 */
export const postCoffeeBean = PosService.method.postCoffeeBean;

/**
 * @generated from rpc cafelogos.pos.PosService.GetCoffeeBeans
 */
export const getCoffeeBeans = PosService.method.getCoffeeBeans;

/**
 * @generated from rpc cafelogos.pos.PosService.DeleteAllOrders
 */
export const deleteAllOrders = PosService.method.deleteAllOrders;

/**
 * @generated from rpc cafelogos.pos.PosService.PostSeat
 */
export const postSeat = PosService.method.postSeat;

/**
 * @generated from rpc cafelogos.pos.PosService.UpdateSeat
 */
export const updateSeat = PosService.method.updateSeat;

/**
 * @generated from rpc cafelogos.pos.PosService.DeleteSeat
 */
export const deleteSeat = PosService.method.deleteSeat;

/**
 * @generated from rpc cafelogos.pos.PosService.GetSeats
 */
export const getSeats = PosService.method.getSeats;

/**
 * @generated from rpc cafelogos.pos.PosService.GetDiscounts
 */
export const getDiscounts = PosService.method.getDiscounts;

/**
 * @generated from rpc cafelogos.pos.PosService.PostDiscount
 */
export const postDiscount = PosService.method.postDiscount;

/**
 * @generated from rpc cafelogos.pos.PosService.GetDailySales
 */
export const getDailySales = PosService.method.getDailySales;

/**
 * @generated from rpc cafelogos.pos.PosService.GetProductSales
 */
export const getProductSales = PosService.method.getProductSales;

/**
 * 売上分析用のメソッド
 *
 * @generated from rpc cafelogos.pos.PosService.GetSalesByTimeSlot
 */
export const getSalesByTimeSlot = PosService.method.getSalesByTimeSlot;

/**
 * @generated from rpc cafelogos.pos.PosService.GetSalesByPaymentType
 */
export const getSalesByPaymentType = PosService.method.getSalesByPaymentType;
