// @generated by protoc-gen-es v2.2.3 with parameter "target=ts+js+dts"
// @generated from file ticket/ticket_service.proto (package cafelogos.ticket, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file ticket/ticket_service.proto.
 */
export const file_ticket_ticket_service = /*@__PURE__*/
  fileDesc("Cht0aWNrZXQvdGlja2V0X3NlcnZpY2UucHJvdG8SEGNhZmVsb2dvcy50aWNrZXQiJAoSUmVxdWVzdElzc3VlVGlja2V0Eg4KBnByZWZpeBgBIAEoCSI/ChNSZXNwb25zZUlzc3VlVGlja2V0EigKBnRpY2tldBgBIAEoCzIYLmNhZmVsb2dvcy50aWNrZXQuVGlja2V0IiEKE1JlcXVlc3RSZXZva2VUaWNrZXQSCgoCaWQYASABKAkiFgoUUmVzcG9uc2VSZXZva2VUaWNrZXQiPQoGVGlja2V0EgoKAmlkGAEgASgJEhMKC3RpY2tldF9hZGRyGAIgASgJEhIKCmNyZWF0ZWRfYXQYAyABKAkyzgEKDVRpY2tldFNlcnZpY2USXAoLSXNzdWVUaWNrZXQSJC5jYWZlbG9nb3MudGlja2V0LlJlcXVlc3RJc3N1ZVRpY2tldBolLmNhZmVsb2dvcy50aWNrZXQuUmVzcG9uc2VJc3N1ZVRpY2tldCIAEl8KDFJldm9rZVRpY2tldBIlLmNhZmVsb2dvcy50aWNrZXQuUmVxdWVzdFJldm9rZVRpY2tldBomLmNhZmVsb2dvcy50aWNrZXQuUmVzcG9uc2VSZXZva2VUaWNrZXQiAEI7WjlnaXRodWIuY29tL0thZ3VyYUdhdGV3YXkvbG9nb3NvbmUvcHJvdG8vcGtnL3RpY2tldDt0aWNrZXRiBnByb3RvMw");

/**
 * Describes the message cafelogos.ticket.RequestIssueTicket.
 * Use `create(RequestIssueTicketSchema)` to create a new message.
 */
export const RequestIssueTicketSchema = /*@__PURE__*/
  messageDesc(file_ticket_ticket_service, 0);

/**
 * Describes the message cafelogos.ticket.ResponseIssueTicket.
 * Use `create(ResponseIssueTicketSchema)` to create a new message.
 */
export const ResponseIssueTicketSchema = /*@__PURE__*/
  messageDesc(file_ticket_ticket_service, 1);

/**
 * Describes the message cafelogos.ticket.RequestRevokeTicket.
 * Use `create(RequestRevokeTicketSchema)` to create a new message.
 */
export const RequestRevokeTicketSchema = /*@__PURE__*/
  messageDesc(file_ticket_ticket_service, 2);

/**
 * Describes the message cafelogos.ticket.ResponseRevokeTicket.
 * Use `create(ResponseRevokeTicketSchema)` to create a new message.
 */
export const ResponseRevokeTicketSchema = /*@__PURE__*/
  messageDesc(file_ticket_ticket_service, 3);

/**
 * Describes the message cafelogos.ticket.Ticket.
 * Use `create(TicketSchema)` to create a new message.
 */
export const TicketSchema = /*@__PURE__*/
  messageDesc(file_ticket_ticket_service, 4);

/**
 * @generated from service cafelogos.ticket.TicketService
 */
export const TicketService = /*@__PURE__*/
  serviceDesc(file_ticket_ticket_service, 0);

