// Code generated by protoc-gen-connect-swift. DO NOT EDIT.
//
// Source: ticket/ticket_service.proto
//

import Connect
import Foundation
import SwiftProtobuf

public protocol Cafelogos_Ticket_TicketServiceClientInterface: Sendable {

    @discardableResult
    func `issueTicket`(request: Cafelogos_Ticket_RequestIssueTicket, headers: Connect.Headers, completion: @escaping @Sendable (ResponseMessage<Cafelogos_Ticket_ResponseIssueTicket>) -> Void) -> Connect.Cancelable

    @available(iOS 13, *)
    func `issueTicket`(request: Cafelogos_Ticket_RequestIssueTicket, headers: Connect.Headers) async -> ResponseMessage<Cafelogos_Ticket_ResponseIssueTicket>

    @discardableResult
    func `revokeTicket`(request: Cafelogos_Ticket_RequestRevokeTicket, headers: Connect.Headers, completion: @escaping @Sendable (ResponseMessage<Cafelogos_Ticket_ResponseRevokeTicket>) -> Void) -> Connect.Cancelable

    @available(iOS 13, *)
    func `revokeTicket`(request: Cafelogos_Ticket_RequestRevokeTicket, headers: Connect.Headers) async -> ResponseMessage<Cafelogos_Ticket_ResponseRevokeTicket>
}

/// Concrete implementation of `Cafelogos_Ticket_TicketServiceClientInterface`.
public final class Cafelogos_Ticket_TicketServiceClient: Cafelogos_Ticket_TicketServiceClientInterface, Sendable {
    private let client: Connect.ProtocolClientInterface

    public init(client: Connect.ProtocolClientInterface) {
        self.client = client
    }

    @discardableResult
    public func `issueTicket`(request: Cafelogos_Ticket_RequestIssueTicket, headers: Connect.Headers = [:], completion: @escaping @Sendable (ResponseMessage<Cafelogos_Ticket_ResponseIssueTicket>) -> Void) -> Connect.Cancelable {
        return self.client.unary(path: "/cafelogos.ticket.TicketService/IssueTicket", request: request, headers: headers, completion: completion)
    }

    @available(iOS 13, *)
    public func `issueTicket`(request: Cafelogos_Ticket_RequestIssueTicket, headers: Connect.Headers = [:]) async -> ResponseMessage<Cafelogos_Ticket_ResponseIssueTicket> {
        return await self.client.unary(path: "/cafelogos.ticket.TicketService/IssueTicket", request: request, headers: headers)
    }

    @discardableResult
    public func `revokeTicket`(request: Cafelogos_Ticket_RequestRevokeTicket, headers: Connect.Headers = [:], completion: @escaping @Sendable (ResponseMessage<Cafelogos_Ticket_ResponseRevokeTicket>) -> Void) -> Connect.Cancelable {
        return self.client.unary(path: "/cafelogos.ticket.TicketService/RevokeTicket", request: request, headers: headers, completion: completion)
    }

    @available(iOS 13, *)
    public func `revokeTicket`(request: Cafelogos_Ticket_RequestRevokeTicket, headers: Connect.Headers = [:]) async -> ResponseMessage<Cafelogos_Ticket_ResponseRevokeTicket> {
        return await self.client.unary(path: "/cafelogos.ticket.TicketService/RevokeTicket", request: request, headers: headers)
    }

    public enum Metadata {
        public enum Methods {
            public static let issueTicket = Connect.MethodSpec(name: "IssueTicket", service: "cafelogos.ticket.TicketService", type: .unary)
            public static let revokeTicket = Connect.MethodSpec(name: "RevokeTicket", service: "cafelogos.ticket.TicketService", type: .unary)
        }
    }
}
