// @generated by protoc-gen-connect-query v0.4.4
// @generated from file pos/pos_service.proto (package cafelogos.pos, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { DeleteOrderRequest, DeleteProductRequest, GetCoffeeBeansResponse, GetOrderBySeatIdRequest, GetOrderResponse, GetOrdersRequest, GetOrdersResponse, GetProductCategoriesResponse, GetProductsResponse, GetSeatsResponse, GetStocksResponse, PostCoffeeBeanRequest, PostOrderPaymentRequest, PostOrderRequest, PostProductCategoryRequest, PostProductRequest, PostSeatRequest, PostStockRequest, UpdateProductRequest, UpdateSeatRequest } from "./pos_service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";
import { Empty } from "../common/common_pb.js";
import { UnaryHooks } from "@connectrpc/connect-query";

/**
 * @generated from service cafelogos.pos.PosService
 */
export declare const PosService: {
  readonly typeName: "cafelogos.pos.PosService",
  readonly methods: {
    /**
     * @generated from rpc cafelogos.pos.PosService.GetOrders
     */
    readonly getOrders: {
      readonly name: "GetOrders",
      readonly I: typeof GetOrdersRequest,
      readonly O: typeof GetOrdersResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cafelogos.pos.PosService.GetOrderBySeatId
     */
    readonly getOrderBySeatId: {
      readonly name: "GetOrderBySeatId",
      readonly I: typeof GetOrderBySeatIdRequest,
      readonly O: typeof GetOrderResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cafelogos.pos.PosService.PostOrder
     */
    readonly postOrder: {
      readonly name: "PostOrder",
      readonly I: typeof PostOrderRequest,
      readonly O: typeof Empty,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cafelogos.pos.PosService.DeleteOrder
     */
    readonly deleteOrder: {
      readonly name: "DeleteOrder",
      readonly I: typeof DeleteOrderRequest,
      readonly O: typeof Empty,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cafelogos.pos.PosService.PostOrderPayment
     */
    readonly postOrderPayment: {
      readonly name: "PostOrderPayment",
      readonly I: typeof PostOrderPaymentRequest,
      readonly O: typeof Empty,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cafelogos.pos.PosService.GetProducts
     */
    readonly getProducts: {
      readonly name: "GetProducts",
      readonly I: typeof Empty,
      readonly O: typeof GetProductsResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * Only Admin
     *
     * @generated from rpc cafelogos.pos.PosService.GetProductCategories
     */
    readonly getProductCategories: {
      readonly name: "GetProductCategories",
      readonly I: typeof Empty,
      readonly O: typeof GetProductCategoriesResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cafelogos.pos.PosService.PostProductCategory
     */
    readonly postProductCategory: {
      readonly name: "PostProductCategory",
      readonly I: typeof PostProductCategoryRequest,
      readonly O: typeof Empty,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cafelogos.pos.PosService.PostProduct
     */
    readonly postProduct: {
      readonly name: "PostProduct",
      readonly I: typeof PostProductRequest,
      readonly O: typeof Empty,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cafelogos.pos.PosService.UpdateProduct
     */
    readonly updateProduct: {
      readonly name: "UpdateProduct",
      readonly I: typeof UpdateProductRequest,
      readonly O: typeof Empty,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cafelogos.pos.PosService.DeleteProduct
     */
    readonly deleteProduct: {
      readonly name: "DeleteProduct",
      readonly I: typeof DeleteProductRequest,
      readonly O: typeof Empty,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cafelogos.pos.PosService.PostStock
     */
    readonly postStock: {
      readonly name: "PostStock",
      readonly I: typeof PostStockRequest,
      readonly O: typeof Empty,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cafelogos.pos.PosService.GetStocks
     */
    readonly getStocks: {
      readonly name: "GetStocks",
      readonly I: typeof Empty,
      readonly O: typeof GetStocksResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cafelogos.pos.PosService.PostCoffeeBean
     */
    readonly postCoffeeBean: {
      readonly name: "PostCoffeeBean",
      readonly I: typeof PostCoffeeBeanRequest,
      readonly O: typeof Empty,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cafelogos.pos.PosService.GetCoffeeBeans
     */
    readonly getCoffeeBeans: {
      readonly name: "GetCoffeeBeans",
      readonly I: typeof Empty,
      readonly O: typeof GetCoffeeBeansResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cafelogos.pos.PosService.DeleteAllOrders
     */
    readonly deleteAllOrders: {
      readonly name: "DeleteAllOrders",
      readonly I: typeof Empty,
      readonly O: typeof Empty,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cafelogos.pos.PosService.PostSeat
     */
    readonly postSeat: {
      readonly name: "PostSeat",
      readonly I: typeof PostSeatRequest,
      readonly O: typeof Empty,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cafelogos.pos.PosService.UpdateSeat
     */
    readonly updateSeat: {
      readonly name: "UpdateSeat",
      readonly I: typeof UpdateSeatRequest,
      readonly O: typeof Empty,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cafelogos.pos.PosService.GetSeats
     */
    readonly getSeats: {
      readonly name: "GetSeats",
      readonly I: typeof Empty,
      readonly O: typeof GetSeatsResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

export const getOrders: UnaryHooks<GetOrdersRequest, GetOrdersResponse>;
export const getOrderBySeatId: UnaryHooks<GetOrderBySeatIdRequest, GetOrderResponse>;
export const postOrder: UnaryHooks<PostOrderRequest, Empty>;
export const deleteOrder: UnaryHooks<DeleteOrderRequest, Empty>;
export const postOrderPayment: UnaryHooks<PostOrderPaymentRequest, Empty>;
export const getProducts: UnaryHooks<Empty, GetProductsResponse>;
export const getProductCategories: UnaryHooks<Empty, GetProductCategoriesResponse>;
export const postProductCategory: UnaryHooks<PostProductCategoryRequest, Empty>;
export const postProduct: UnaryHooks<PostProductRequest, Empty>;
export const updateProduct: UnaryHooks<UpdateProductRequest, Empty>;
export const deleteProduct: UnaryHooks<DeleteProductRequest, Empty>;
export const postStock: UnaryHooks<PostStockRequest, Empty>;
export const getStocks: UnaryHooks<Empty, GetStocksResponse>;
export const postCoffeeBean: UnaryHooks<PostCoffeeBeanRequest, Empty>;
export const getCoffeeBeans: UnaryHooks<Empty, GetCoffeeBeansResponse>;
export const deleteAllOrders: UnaryHooks<Empty, Empty>;
export const postSeat: UnaryHooks<PostSeatRequest, Empty>;
export const updateSeat: UnaryHooks<UpdateSeatRequest, Empty>;
export const getSeats: UnaryHooks<Empty, GetSeatsResponse>;
