// @generated by protoc-gen-es v2.2.3 with parameter "target=ts+js+dts"
// @generated from file common/common.proto (package cafelogos.common, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file common/common.proto.
 */
export const file_common_common = /*@__PURE__*/
  fileDesc("ChNjb21tb24vY29tbW9uLnByb3RvEhBjYWZlbG9nb3MuY29tbW9uIgcKBUVtcHR5QjtaOWdpdGh1Yi5jb20vS2FndXJhR2F0ZXdheS9jYWZlbG9nb3MtZ3JwYy9wa2cvY29tbW9uO2NvbW1vbmIGcHJvdG8z");

/**
 * Describes the message cafelogos.common.Empty.
 * Use `create(EmptySchema)` to create a new message.
 */
export const EmptySchema = /*@__PURE__*/
  messageDesc(file_common_common, 0);

