// @generated by protoc-gen-es v1.10.0 with parameter "target=ts+js+dts"
// @generated from file orderlink/orderlink_service.proto (package cafelogos.orderlink, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message cafelogos.orderlink.PostOrderItemInput
 */
export const PostOrderItemInput = /*@__PURE__*/ proto3.makeMessageType(
  "cafelogos.orderlink.PostOrderItemInput",
  () => [
    { no: 1, name: "product_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "coffee_brew_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "quantity", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 20, name: "is_managing_order", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 21, name: "is_ol_kitchen", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

/**
 * @generated from message cafelogos.orderlink.PostOrderInput
 */
export const PostOrderInput = /*@__PURE__*/ proto3.makeMessageType(
  "cafelogos.orderlink.PostOrderInput",
  () => [
    { no: 1, name: "order_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "order_at", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "items", kind: "message", T: PostOrderItemInput, repeated: true },
    { no: 4, name: "type", kind: "enum", T: proto3.getEnumType(PostOrderInput_OrderType) },
    { no: 5, name: "ticket_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "ticket_addr", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "seat_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from enum cafelogos.orderlink.PostOrderInput.OrderType
 */
export const PostOrderInput_OrderType = /*@__PURE__*/ proto3.makeEnum(
  "cafelogos.orderlink.PostOrderInput.OrderType",
  [
    {no: 0, name: "EAT_IN"},
    {no: 1, name: "TAKE_OUT"},
  ],
);

