// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts+js+dts"
// @generated from file orderlink/orderlink_service.proto (package cafelogos.orderlink, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { PostOrderInput } from "./orderlink_service_pb.js";
import { Empty } from "../common/common_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service cafelogos.orderlink.OrderLinkService
 */
export declare const OrderLinkService: {
  readonly typeName: "cafelogos.orderlink.OrderLinkService",
  readonly methods: {
    /**
     * @generated from rpc cafelogos.orderlink.OrderLinkService.PostOrder
     */
    readonly postOrder: {
      readonly name: "PostOrder",
      readonly I: typeof PostOrderInput,
      readonly O: typeof Empty,
      readonly kind: MethodKind.Unary,
    },
  }
};

