// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.2
// source: proto/ticket_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TicketServiceClient is the client API for TicketService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TicketServiceClient interface {
	IssueTicket(ctx context.Context, in *RequestIssueTicket, opts ...grpc.CallOption) (*ResponseIssueTicket, error)
	RevokeTicket(ctx context.Context, in *RequestRevokeTicket, opts ...grpc.CallOption) (*ResponseRevokeTicket, error)
}

type ticketServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTicketServiceClient(cc grpc.ClientConnInterface) TicketServiceClient {
	return &ticketServiceClient{cc}
}

func (c *ticketServiceClient) IssueTicket(ctx context.Context, in *RequestIssueTicket, opts ...grpc.CallOption) (*ResponseIssueTicket, error) {
	out := new(ResponseIssueTicket)
	err := c.cc.Invoke(ctx, "/cafelogos.TicketService/IssueTicket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) RevokeTicket(ctx context.Context, in *RequestRevokeTicket, opts ...grpc.CallOption) (*ResponseRevokeTicket, error) {
	out := new(ResponseRevokeTicket)
	err := c.cc.Invoke(ctx, "/cafelogos.TicketService/RevokeTicket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TicketServiceServer is the server API for TicketService service.
// All implementations should embed UnimplementedTicketServiceServer
// for forward compatibility
type TicketServiceServer interface {
	IssueTicket(context.Context, *RequestIssueTicket) (*ResponseIssueTicket, error)
	RevokeTicket(context.Context, *RequestRevokeTicket) (*ResponseRevokeTicket, error)
}

// UnimplementedTicketServiceServer should be embedded to have forward compatible implementations.
type UnimplementedTicketServiceServer struct {
}

func (UnimplementedTicketServiceServer) IssueTicket(context.Context, *RequestIssueTicket) (*ResponseIssueTicket, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IssueTicket not implemented")
}
func (UnimplementedTicketServiceServer) RevokeTicket(context.Context, *RequestRevokeTicket) (*ResponseRevokeTicket, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeTicket not implemented")
}

// UnsafeTicketServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TicketServiceServer will
// result in compilation errors.
type UnsafeTicketServiceServer interface {
	mustEmbedUnimplementedTicketServiceServer()
}

func RegisterTicketServiceServer(s grpc.ServiceRegistrar, srv TicketServiceServer) {
	s.RegisterService(&TicketService_ServiceDesc, srv)
}

func _TicketService_IssueTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestIssueTicket)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).IssueTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cafelogos.TicketService/IssueTicket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).IssueTicket(ctx, req.(*RequestIssueTicket))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_RevokeTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestRevokeTicket)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).RevokeTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cafelogos.TicketService/RevokeTicket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).RevokeTicket(ctx, req.(*RequestRevokeTicket))
	}
	return interceptor(ctx, in, info, handler)
}

// TicketService_ServiceDesc is the grpc.ServiceDesc for TicketService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TicketService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cafelogos.TicketService",
	HandlerType: (*TicketServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IssueTicket",
			Handler:    _TicketService_IssueTicket_Handler,
		},
		{
			MethodName: "RevokeTicket",
			Handler:    _TicketService_RevokeTicket_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ticket_service.proto",
}
