name: Biome Lint

"on":
  push:
    paths:
      - 'orderlink-frontend/**'
  pull_request:
    paths:
      - 'orderlink-frontend/**'

jobs:
  lint:
    name: Run Biome Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./orderlink-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Biome lint
        run: npm run lint
