name: PR-Agent

on:
  pull_request:
    types: [opened, reopened, ready_for_review]

permissions:
  issues: write
  pull-requests: write

jobs:
  pr_agent_job:
    runs-on: ubuntu-latest
    name: Run pr agent on every pull request
    if: ${{ github.event.sender.type != 'Bot' }}
    env:
      COMMON_INSTRUCTIONS: >-
        - 日本語で回答してください
        - 利用技術
          - Frontend: Next.js(Page Router)
          - Backend: Golang
    steps:
      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTION_CONFIG.AUTO_DESCRIBE: true
          GITHUB_ACTION_CONFIG.AUTO_REVIEW: true
          GITHUB_ACTION_CONFIG.AUTO_IMPROVE: true
          PR_REVIEWER.EXTRA_INSTRUCTIONS: ${{ env.COMMON_INSTRUCTIONS }}
          PR_CODE_SUGGESTION.EXTRA_INSTRUCTIONS: ${{ env.COMMON_INSTRUCTIONS }}
          PR_DESCRIPTION.EXTRA_INSTRUCTIONS: ${{ env.COMMON_INSTRUCTIONS }}
          CONFIG.MODEL: o1-mini
