version: '3'
services:
  db:
    image: postgres:15
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
  redis:
    image: redis:7
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

volumes:
  db-data:
  redis-data:
