// @generated by protoc-gen-connect-query v1.4.2 with parameter "target=ts+js+dts"
// @generated from file orderlink/orderlink_service.proto (package cafelogos.orderlink, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { PostOrderInput } from "./orderlink_service_pb.js";
import { Empty } from "../common/common_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from rpc cafelogos.orderlink.OrderLinkService.PostOrder
 */
export const postOrder: {
      readonly name: "PostOrder",
      readonly I: typeof PostOrderInput,
      readonly O: typeof Empty,
      readonly kind: MethodKind.Unary,
  readonly service: {
    readonly typeName: "cafelogos.orderlink.OrderLinkService"
  }
};
