// @generated by protoc-gen-es v2.2.3 with parameter "target=ts+js+dts"
// @generated from file orderlink/orderlink_service.proto (package cafelogos.orderlink, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, serviceDesc, tsEnum } from "@bufbuild/protobuf/codegenv1";
import { file_common_common } from "../common/common_pb";

/**
 * Describes the file orderlink/orderlink_service.proto.
 */
export const file_orderlink_orderlink_service = /*@__PURE__*/
  fileDesc("CiFvcmRlcmxpbmsvb3JkZXJsaW5rX3NlcnZpY2UucHJvdG8SE2NhZmVsb2dvcy5vcmRlcmxpbmsihAEKElBvc3RPcmRlckl0ZW1JbnB1dBISCgpwcm9kdWN0X2lkGAEgASgJEhYKDmNvZmZlZV9icmV3X2lkGAIgASgJEhAKCHF1YW50aXR5GAMgASgNEhkKEWlzX21hbmFnaW5nX29yZGVyGBQgASgIEhUKDWlzX29sX2tpdGNoZW4YFSABKAgiiwIKDlBvc3RPcmRlcklucHV0EhAKCG9yZGVyX2lkGAEgASgJEhAKCG9yZGVyX2F0GAIgASgJEjYKBWl0ZW1zGAMgAygLMicuY2FmZWxvZ29zLm9yZGVybGluay5Qb3N0T3JkZXJJdGVtSW5wdXQSOwoEdHlwZRgEIAEoDjItLmNhZmVsb2dvcy5vcmRlcmxpbmsuUG9zdE9yZGVySW5wdXQuT3JkZXJUeXBlEhEKCXRpY2tldF9pZBgFIAEoCRITCgt0aWNrZXRfYWRkchgGIAEoCRIRCglzZWF0X25hbWUYByABKAkiJQoJT3JkZXJUeXBlEgoKBkVBVF9JThAAEgwKCFRBS0VfT1VUEAEyXwoQT3JkZXJMaW5rU2VydmljZRJLCglQb3N0T3JkZXISIy5jYWZlbG9nb3Mub3JkZXJsaW5rLlBvc3RPcmRlcklucHV0GhcuY2FmZWxvZ29zLmNvbW1vbi5FbXB0eSIAQkFaP2dpdGh1Yi5jb20vS2FndXJhR2F0ZXdheS9sb2dvc29uZS9wcm90by9wa2cvb3JkZXJsaW5rO29yZGVybGlua2IGcHJvdG8z", [file_common_common]);

/**
 * Describes the message cafelogos.orderlink.PostOrderItemInput.
 * Use `create(PostOrderItemInputSchema)` to create a new message.
 */
export const PostOrderItemInputSchema = /*@__PURE__*/
  messageDesc(file_orderlink_orderlink_service, 0);

/**
 * Describes the message cafelogos.orderlink.PostOrderInput.
 * Use `create(PostOrderInputSchema)` to create a new message.
 */
export const PostOrderInputSchema = /*@__PURE__*/
  messageDesc(file_orderlink_orderlink_service, 1);

/**
 * Describes the enum cafelogos.orderlink.PostOrderInput.OrderType.
 */
export const PostOrderInput_OrderTypeSchema = /*@__PURE__*/
  enumDesc(file_orderlink_orderlink_service, 1, 0);

/**
 * @generated from enum cafelogos.orderlink.PostOrderInput.OrderType
 */
export const PostOrderInput_OrderType = /*@__PURE__*/
  tsEnum(PostOrderInput_OrderTypeSchema);

/**
 * @generated from service cafelogos.orderlink.OrderLinkService
 */
export const OrderLinkService = /*@__PURE__*/
  serviceDesc(file_orderlink_orderlink_service, 0);

