// @generated by protoc-gen-es v2.2.3 with parameter "target=ts+js+dts"
// @generated from file orderlink/orderlink_service.proto (package cafelogos.orderlink, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, serviceDesc, tsEnum } from "@bufbuild/protobuf/codegenv1";
import { file_common_common } from "../common/common_pb";

/**
 * Describes the file orderlink/orderlink_service.proto.
 */
export const file_orderlink_orderlink_service = /*@__PURE__*/
  fileDesc("CiFvcmRlcmxpbmsvb3JkZXJsaW5rX3NlcnZpY2UucHJvdG8SE2NhZmVsb2dvcy5vcmRlcmxpbmsikwMKEkxpc3RPcmRlcnNSZXNwb25zZRIQCghvcmRlcl9pZBgBIAEoCRIQCghvcmRlcl9hdBgCIAEoCRI/CgR0eXBlGAMgASgOMjEuY2FmZWxvZ29zLm9yZGVybGluay5MaXN0T3JkZXJzUmVzcG9uc2UuT3JkZXJUeXBlEhEKCXRpY2tldF9pZBgEIAEoCRITCgt0aWNrZXRfYWRkchgFIAEoCRIRCglzZWF0X25hbWUYBiABKAkSQwoGc3RhdXRzGAcgASgOMjMuY2FmZWxvZ29zLm9yZGVybGluay5MaXN0T3JkZXJzUmVzcG9uc2UuT3JkZXJTdGF0dXMSFgoJc2VydmVkX2F0GAggASgJSACIAQEiJQoJT3JkZXJUeXBlEgoKBkVBVF9JThAAEgwKCFRBS0VfT1VUEAEiSwoLT3JkZXJTdGF0dXMSCgoGTm90WWV0EAASCwoHQ29va2luZxABEgoKBkNvb2tlZBACEgsKB0NhbGxpbmcQAxIKCgZTZXJ2ZWQQBEIMCgpfc2VydmVkX2F0IicKEEdldFdhaXRUaW1lSW5wdXQSEwoLcHJvZHVjdF9pZHMYASADKAkiLgoRR2V0V2FpdFRpbWVPdXRwdXQSGQoRd2FpdF90aW1lX21pbnV0ZXMYASABKA0ihAEKElBvc3RPcmRlckl0ZW1JbnB1dBISCgpwcm9kdWN0X2lkGAEgASgJEhYKDmNvZmZlZV9icmV3X2lkGAIgASgJEhAKCHF1YW50aXR5GAMgASgNEhkKEWlzX21hbmFnaW5nX29yZGVyGBQgASgIEhUKDWlzX29sX2tpdGNoZW4YFSABKAgiiwIKDlBvc3RPcmRlcklucHV0EhAKCG9yZGVyX2lkGAEgASgJEhAKCG9yZGVyX2F0GAIgASgJEjYKBWl0ZW1zGAMgAygLMicuY2FmZWxvZ29zLm9yZGVybGluay5Qb3N0T3JkZXJJdGVtSW5wdXQSOwoEdHlwZRgEIAEoDjItLmNhZmVsb2dvcy5vcmRlcmxpbmsuUG9zdE9yZGVySW5wdXQuT3JkZXJUeXBlEhEKCXRpY2tldF9pZBgFIAEoCRITCgt0aWNrZXRfYWRkchgGIAEoCRIRCglzZWF0X25hbWUYByABKAkiJQoJT3JkZXJUeXBlEgoKBkVBVF9JThAAEgwKCFRBS0VfT1VUEAEykQIKEE9yZGVyTGlua1NlcnZpY2USSwoJUG9zdE9yZGVyEiMuY2FmZWxvZ29zLm9yZGVybGluay5Qb3N0T3JkZXJJbnB1dBoXLmNhZmVsb2dvcy5jb21tb24uRW1wdHkiABJeCgtHZXRXYWl0VGltZRIlLmNhZmVsb2dvcy5vcmRlcmxpbmsuR2V0V2FpdFRpbWVJbnB1dBomLmNhZmVsb2dvcy5vcmRlcmxpbmsuR2V0V2FpdFRpbWVPdXRwdXQiABJQCgpMaXN0T3JkZXJzEhcuY2FmZWxvZ29zLmNvbW1vbi5FbXB0eRonLmNhZmVsb2dvcy5vcmRlcmxpbmsuTGlzdE9yZGVyc1Jlc3BvbnNlIgBCQVo/Z2l0aHViLmNvbS9LYWd1cmFHYXRld2F5L2NhZmVsb2dvcy1ncnBjL3BrZy9vcmRlcmxpbms7b3JkZXJsaW5rYgZwcm90bzM", [file_common_common]);

/**
 * Describes the message cafelogos.orderlink.ListOrdersResponse.
 * Use `create(ListOrdersResponseSchema)` to create a new message.
 */
export const ListOrdersResponseSchema = /*@__PURE__*/
  messageDesc(file_orderlink_orderlink_service, 0);

/**
 * Describes the enum cafelogos.orderlink.ListOrdersResponse.OrderType.
 */
export const ListOrdersResponse_OrderTypeSchema = /*@__PURE__*/
  enumDesc(file_orderlink_orderlink_service, 0, 0);

/**
 * @generated from enum cafelogos.orderlink.ListOrdersResponse.OrderType
 */
export const ListOrdersResponse_OrderType = /*@__PURE__*/
  tsEnum(ListOrdersResponse_OrderTypeSchema);

/**
 * Describes the enum cafelogos.orderlink.ListOrdersResponse.OrderStatus.
 */
export const ListOrdersResponse_OrderStatusSchema = /*@__PURE__*/
  enumDesc(file_orderlink_orderlink_service, 0, 1);

/**
 * @generated from enum cafelogos.orderlink.ListOrdersResponse.OrderStatus
 */
export const ListOrdersResponse_OrderStatus = /*@__PURE__*/
  tsEnum(ListOrdersResponse_OrderStatusSchema);

/**
 * Describes the message cafelogos.orderlink.GetWaitTimeInput.
 * Use `create(GetWaitTimeInputSchema)` to create a new message.
 */
export const GetWaitTimeInputSchema = /*@__PURE__*/
  messageDesc(file_orderlink_orderlink_service, 1);

/**
 * Describes the message cafelogos.orderlink.GetWaitTimeOutput.
 * Use `create(GetWaitTimeOutputSchema)` to create a new message.
 */
export const GetWaitTimeOutputSchema = /*@__PURE__*/
  messageDesc(file_orderlink_orderlink_service, 2);

/**
 * Describes the message cafelogos.orderlink.PostOrderItemInput.
 * Use `create(PostOrderItemInputSchema)` to create a new message.
 */
export const PostOrderItemInputSchema = /*@__PURE__*/
  messageDesc(file_orderlink_orderlink_service, 3);

/**
 * Describes the message cafelogos.orderlink.PostOrderInput.
 * Use `create(PostOrderInputSchema)` to create a new message.
 */
export const PostOrderInputSchema = /*@__PURE__*/
  messageDesc(file_orderlink_orderlink_service, 4);

/**
 * Describes the enum cafelogos.orderlink.PostOrderInput.OrderType.
 */
export const PostOrderInput_OrderTypeSchema = /*@__PURE__*/
  enumDesc(file_orderlink_orderlink_service, 4, 0);

/**
 * @generated from enum cafelogos.orderlink.PostOrderInput.OrderType
 */
export const PostOrderInput_OrderType = /*@__PURE__*/
  tsEnum(PostOrderInput_OrderTypeSchema);

/**
 * @generated from service cafelogos.orderlink.OrderLinkService
 */
export const OrderLinkService = /*@__PURE__*/
  serviceDesc(file_orderlink_orderlink_service, 0);

