// @generated by protoc-gen-connect-query v2.2.0 with parameter "target=ts+js+dts"
// @generated from file orderlink/orderlink_service.proto (package cafelogos.orderlink, syntax proto3)
/* eslint-disable */

import { OrderLinkService } from "./orderlink_service_pb";

/**
 * @generated from rpc cafelogos.orderlink.OrderLinkService.PostOrder
 */
export const postOrder: typeof OrderLinkService["method"]["postOrder"];
