// @generated by protoc-gen-es v2.12.0 with parameter "target=ts+js+dts"
// @generated from file orderlink/orderlink_service.proto (package cafelogos.orderlink, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { EmptySchema } from "../common/common_pb";
import { file_common_common } from "../common/common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file orderlink/orderlink_service.proto.
 */
export const file_orderlink_orderlink_service: GenFile = /*@__PURE__*/
  fileDesc("CiFvcmRlcmxpbmsvb3JkZXJsaW5rX3NlcnZpY2UucHJvdG8SE2NhZmVsb2dvcy5vcmRlcmxpbmsihAEKElBvc3RPcmRlckl0ZW1JbnB1dBISCgpwcm9kdWN0X2lkGAEgASgJEhYKDmNvZmZlZV9icmV3X2lkGAIgASgJEhAKCHF1YW50aXR5GAMgASgNEhkKEWlzX21hbmFnaW5nX29yZGVyGBQgASgIEhUKDWlzX29sX2tpdGNoZW4YFSABKAgiiwIKDlBvc3RPcmRlcklucHV0EhAKCG9yZGVyX2lkGAEgASgJEhAKCG9yZGVyX2F0GAIgASgJEjYKBWl0ZW1zGAMgAygLMicuY2FmZWxvZ29zLm9yZGVybGluay5Qb3N0T3JkZXJJdGVtSW5wdXQSOwoEdHlwZRgEIAEoDjItLmNhZmVsb2dvcy5vcmRlcmxpbmsuUG9zdE9yZGVySW5wdXQuT3JkZXJUeXBlEhEKCXRpY2tldF9pZBgFIAEoCRITCgt0aWNrZXRfYWRkchgGIAEoCRIRCglzZWF0X25hbWUYByABKAkiJQoJT3JkZXJUeXBlEgoKBkVBVF9JThAAEgwKCFRBS0VfT1VUEAEiJAoQQ2FuY2VsT3JkZXJJbnB1dBIQCghvcmRlcl9pZBgBIAEoCSJHChFDYW5jZWxPcmRlck91dHB1dBIyCgVpdGVtcxgBIAMoCzIjLmNhZmVsb2dvcy5vcmRlcmxpbmsuQ2FuY2VsSXRlbUluZm8iNAoOQ2FuY2VsSXRlbUluZm8SEgoKcHJvZHVjdF9pZBgBIAEoCRIOCgZzdGF0dXMYAiABKAUysAEKEE9yZGVyTGlua1NlcnZpY2USSwoJUG9zdE9yZGVyEiMuY2FmZWxvZ29zLm9yZGVybGluay5Qb3N0T3JkZXJJbnB1dBoXLmNhZmVsb2dvcy5jb21tb24uRW1wdHkiABJPCgtDYW5jZWxPcmRlchIlLmNhZmVsb2dvcy5vcmRlcmxpbmsuQ2FuY2VsT3JkZXJJbnB1dBoXLmNhZmVsb2dvcy5jb21tb24uRW1wdHkiAEJBWj9naXRodWIuY29tL0thZ3VyYUdhdGV3YXkvY2FmZWxvZ29zLWdycGMvcGtnL29yZGVybGluaztvcmRlcmxpbmtiBnByb3RvMw", [file_common_common]);

/**
 * @generated from message cafelogos.orderlink.PostOrderItemInput
 */
export type PostOrderItemInput = Message<"cafelogos.orderlink.PostOrderItemInput"> & {
  /**
   * @generated from field: string product_id = 1;
   */
  productId: string;

  /**
   * @generated from field: string coffee_brew_id = 2;
   */
  coffeeBrewId: string;

  /**
   * @generated from field: uint32 quantity = 3;
   */
  quantity: number;

  /**
   * 注文管理を行うかどうか
   *
   * @generated from field: bool is_managing_order = 20;
   */
  isManagingOrder: boolean;

  /**
   * OrderLinkでキッチン機能を使うかどうか
   *
   * @generated from field: bool is_ol_kitchen = 21;
   */
  isOlKitchen: boolean;
};

/**
 * Describes the message cafelogos.orderlink.PostOrderItemInput.
 * Use `create(PostOrderItemInputSchema)` to create a new message.
 */
export const PostOrderItemInputSchema: GenMessage<PostOrderItemInput> = /*@__PURE__*/
  messageDesc(file_orderlink_orderlink_service, 0);

/**
 * @generated from message cafelogos.orderlink.PostOrderInput
 */
export type PostOrderInput = Message<"cafelogos.orderlink.PostOrderInput"> & {
  /**
   * @generated from field: string order_id = 1;
   */
  orderId: string;

  /**
   * @generated from field: string order_at = 2;
   */
  orderAt: string;

  /**
   * @generated from field: repeated cafelogos.orderlink.PostOrderItemInput items = 3;
   */
  items: PostOrderItemInput[];

  /**
   * @generated from field: cafelogos.orderlink.PostOrderInput.OrderType type = 4;
   */
  type: PostOrderInput_OrderType;

  /**
   * @generated from field: string ticket_id = 5;
   */
  ticketId: string;

  /**
   * @generated from field: string ticket_addr = 6;
   */
  ticketAddr: string;

  /**
   * @generated from field: string seat_name = 7;
   */
  seatName: string;
};

/**
 * Describes the message cafelogos.orderlink.PostOrderInput.
 * Use `create(PostOrderInputSchema)` to create a new message.
 */
export const PostOrderInputSchema: GenMessage<PostOrderInput> = /*@__PURE__*/
  messageDesc(file_orderlink_orderlink_service, 1);

/**
 * @generated from enum cafelogos.orderlink.PostOrderInput.OrderType
 */
export enum PostOrderInput_OrderType {
  /**
   * @generated from enum value: EAT_IN = 0;
   */
  EAT_IN = 0,

  /**
   * @generated from enum value: TAKE_OUT = 1;
   */
  TAKE_OUT = 1,
}

/**
 * Describes the enum cafelogos.orderlink.PostOrderInput.OrderType.
 */
export const PostOrderInput_OrderTypeSchema: GenEnum<PostOrderInput_OrderType> = /*@__PURE__*/
  enumDesc(file_orderlink_orderlink_service, 1, 0);

/**
 * @generated from message cafelogos.orderlink.CancelOrderInput
 */
export type CancelOrderInput = Message<"cafelogos.orderlink.CancelOrderInput"> & {
  /**
   * @generated from field: string order_id = 1;
   */
  orderId: string;
};

/**
 * Describes the message cafelogos.orderlink.CancelOrderInput.
 * Use `create(CancelOrderInputSchema)` to create a new message.
 */
export const CancelOrderInputSchema: GenMessage<CancelOrderInput> = /*@__PURE__*/
  messageDesc(file_orderlink_orderlink_service, 2);

/**
 * @generated from message cafelogos.orderlink.CancelOrderOutput
 */
export type CancelOrderOutput = Message<"cafelogos.orderlink.CancelOrderOutput"> & {
  /**
   * @generated from field: repeated cafelogos.orderlink.CancelItemInfo items = 1;
   */
  items: CancelItemInfo[];
};

/**
 * Describes the message cafelogos.orderlink.CancelOrderOutput.
 * Use `create(CancelOrderOutputSchema)` to create a new message.
 */
export const CancelOrderOutputSchema: GenMessage<CancelOrderOutput> = /*@__PURE__*/
  messageDesc(file_orderlink_orderlink_service, 3);

/**
 * @generated from message cafelogos.orderlink.CancelItemInfo
 */
export type CancelItemInfo = Message<"cafelogos.orderlink.CancelItemInfo"> & {
  /**
   * @generated from field: string product_id = 1;
   */
  productId: string;

  /**
   * @generated from field: int32 status = 2;
   */
  status: number;
};

/**
 * Describes the message cafelogos.orderlink.CancelItemInfo.
 * Use `create(CancelItemInfoSchema)` to create a new message.
 */
export const CancelItemInfoSchema: GenMessage<CancelItemInfo> = /*@__PURE__*/
  messageDesc(file_orderlink_orderlink_service, 4);

/**
 * @generated from service cafelogos.orderlink.OrderLinkService
 */
export const OrderLinkService: GenService<{
  /**
   * @generated from rpc cafelogos.orderlink.OrderLinkService.PostOrder
   */
  postOrder: {
    methodKind: "unary";
    input: typeof PostOrderInputSchema;
    output: typeof EmptySchema;
  },
  /**
   * @generated from rpc cafelogos.orderlink.OrderLinkService.CancelOrder
   */
  cancelOrder: {
    methodKind: "unary";
    input: typeof CancelOrderInputSchema;
    output: typeof EmptySchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_orderlink_orderlink_service, 0);

